### ISSUE TITLE
exe文件所在的文件夹自动生成的tokens.xrm-ms可以删除或者移动吗？

### ISSUE THREAD

**Issue by lj123454321** [MIAIONE/SPPClient#1]
谢谢大佬，很顺利地激活了。请问exe文件所在的文件夹自动生成的tokens.xrm-ms可以删除或者移动吗？如果删除或者移动了会改变激活状态吗？

**Comment by MIAIONE** [comment]
可以，这个只是genuineticket.xml正版激活许可证别称文件
